const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'sc-manager-test-'));process.env.SC_CONFIG_DIR=path.join(root,'config');
const P=require('../lib/profiles'),C=require('../lib/connections'),{PROVIDERS}=require('../lib/providers'),{startCredentialManager}=require('../lib/credential-manager'),{createCredentialSession}=require('../lib/credential-session');
const KEY='opaque_test_project_key_not_a_real_secret';let counter=0;
async function setup(t,options={}){const user='qa'+(++counter);P.writeProfile(user,{});const m=await startCredentialManager({user,check:async()=>({ok:true}),...options});t.after(()=>m.close());const token=new URL(m.url).hash.slice(1);const headers={Authorization:'Bearer '+token,Origin:m.origin,'Content-Type':'application/json'};const call=async(action,body={},extra={})=>{const r=await fetch(m.origin+'/api/action',{method:'POST',headers:{...headers,...extra},body:JSON.stringify({action,...body})});return {status:r.status,body:await r.json()}};return {...m,user,headers,token,call}}
const select=(s,extra={})=>s.call('select',{selection:{user:s.user,providerId:'composio',newConnection:true,authMethod:'project-api-key',label:'Main project',...extra}});
test.after(()=>fs.rmSync(root,{recursive:true,force:true}));
test('manager exposes every registry provider and source, not a handpicked subset',async t=>{const s=await setup(t);const r=await fetch(s.origin+'/api/catalog',{headers:s.headers});const data=await r.json();assert.deepEqual(data.providers.map(p=>p.id),PROVIDERS.map(p=>p.id));assert.ok(data.providers.find(p=>p.id==='github').sources.some(s=>s.id==='composio'));assert.ok(data.providers.find(p=>p.id==='vercel').sources.some(s=>s.id==='native-mcp'));assert.ok(!JSON.stringify(data).includes(s.token));assert.equal((await fetch(s.origin+'/api/catalog')).status,401)});
test('public HTML has nonce CSP and syntactically valid client code',async t=>{const s=await setup(t);const r=await fetch(s.origin);const h=await r.text();assert.ok(!h.includes(s.token));assert.match(r.headers.get('content-security-policy'),/script-src 'nonce-/);assert.doesNotThrow(()=>new Function(h.match(/<script[^>]*>([\s\S]*?)<\/script>/)[1]))});
test('selection, verified save, metadata-only catalog and replay protection',async t=>{const s=await setup(t);const form=await select(s);assert.equal(form.status,200);assert.equal(form.body.setup.fields.length,1);const saved=await s.call('save',{sessionId:form.body.sessionId,values:{COMPOSIO_API_KEY:KEY}});assert.equal(saved.status,200);assert.equal(saved.body.verified,true);assert.equal((await s.call('save',{sessionId:form.body.sessionId,values:{COMPOSIO_API_KEY:KEY}})).status,401);const catalog=await (await fetch(s.origin+'/api/catalog',{headers:s.headers})).text();assert.ok(!catalog.includes(KEY));assert.equal(fs.statSync(C.connectionPath(s.user,'composio',saved.body.connection)).mode&0o777,0o600)});
test('failed credential checks leave old keys untouched',async t=>{const s=await setup(t,{check:async()=>({ok:false,detail:KEY})});const conn=C.create(s.user,'composio',{label:'Existing',source:'sc',authMethod:'project-api-key'});C.writeValues(s.user,'composio',conn.id,{COMPOSIO_API_KEY:'original_test_credential'});const form=await select(s,{newConnection:false,connectionId:conn.id});const r=await s.call('save',{sessionId:form.body.sessionId,values:{COMPOSIO_API_KEY:KEY},allowUnverified:true,confirmation:'SAVE UNVERIFIED'});assert.equal(r.status,422);assert.equal(r.body.error,'credential_rejected');assert.equal(C.readValues(s.user,'composio',conn.id).COMPOSIO_API_KEY,'original_test_credential')});
test('unverified save requires explicit confirmation and never claims verified',async t=>{const s=await setup(t,{check:async()=>({ok:null})});const form=await select(s);const payload={sessionId:form.body.sessionId,values:{COMPOSIO_API_KEY:KEY}};assert.equal((await s.call('save',payload)).body.error,'verification_unavailable');assert.equal((await s.call('save',{...payload,allowUnverified:true})).status,422);const r=await s.call('save',{...payload,allowUnverified:true,confirmation:'SAVE UNVERIFIED'});assert.equal(r.status,200);assert.equal(r.body.verified,false);assert.equal(r.body.status,'saved_unverified')});
test('named connection creation, rename, default and confirmed deletion',async t=>{const s=await setup(t);const created=await s.call('connection-create',{user:s.user,provider:'composio',source:'sc',authMethod:'project-api-key',label:'Work'});const args={user:s.user,provider:'composio',connection:created.body.connection};assert.equal((await s.call('connection-rename',{...args,label:'Work renamed'})).status,200);assert.equal((await s.call('connection-default',args)).status,200);assert.equal((await s.call('connection-delete',args)).body.error,'confirmation_required');assert.equal((await s.call('connection-delete',{...args,confirmation:'Work renamed'})).status,200);assert.equal(C.list(s.user,'composio').length,0)});
test('user creation is isolated and invalid owners do not leave partial users',async t=>{const s=await setup(t);assert.equal((await s.call('user-create',{user:'new-user',owner:'Owner'})).status,200);assert.ok(P.profileExists('new-user'));assert.notEqual((await s.call('user-create',{user:'invalid-owner-user',owner:'x\ny'})).status,200);assert.equal(P.profileExists('invalid-owner-user'),false)});
test('cross-origin, invalid form, oversized body and expired session rejected',async t=>{const s=await setup(t);assert.equal((await s.call('select',{}, {Origin:'https://evil.invalid'})).status,403);assert.equal((await s.call('save',{sessionId:'not-real',values:{}})).status,400);assert.equal((await s.call('save',{sessionId:'not-real',values:{data:'x'.repeat(18000)}})).status,413);const short=await setup(t,{ttlMs:10});await new Promise(r=>setTimeout(r,15));assert.equal((await short.call('select')).status,401)});
test('method fields cannot be changed after selection or submitted cross-provider',async t=>{const s=await setup(t);const form=await select(s);assert.equal((await s.call('save',{sessionId:form.body.sessionId,values:{HOSTINGER_API_TOKEN:KEY}})).body.error,'invalid_fields');const conn=C.create(s.user,'composio',{label:'Will be removed',source:'sc',authMethod:'project-api-key'});const bound=createCredentialSession({user:s.user,providerId:'composio',connectionId:conn.id},{check:async()=>({ok:true})});C.remove(s.user,'composio',conn.id);await assert.rejects(()=>bound.save({COMPOSIO_API_KEY:KEY}));assert.equal(C.list(s.user,'composio').length,0)});
test('all direct provider methods render without leaking values',async t=>{const s=await setup(t);for(const p of PROVIDERS)for(const method of C.authOptions(p,'sc')){const form=createCredentialSession({user:s.user,providerId:p.id,authMethod:method.id,newConnection:true});const schema=form.schema();assert.equal(schema.method,method.id);assert.deepEqual(schema.fields.map(f=>f.key),p.vars.filter(v=>(method.fields||[]).includes(v.key)).map(v=>v.key));assert.ok(!JSON.stringify(schema).includes(KEY))}});

test('concurrent credential changes are preserved rather than silently overwritten',async t=>{
  const s=await setup(t);const conn=C.create(s.user,'composio',{label:'Concurrent',source:'sc',authMethod:'project-api-key'});C.writeValues(s.user,'composio',conn.id,{COMPOSIO_API_KEY:'original_concurrent_key'});
  const form=createCredentialSession({user:s.user,providerId:'composio',connectionId:conn.id},{check:async()=>{C.writeValues(s.user,'composio',conn.id,{COMPOSIO_API_KEY:'new_concurrent_key_keep_me'});return {ok:true}}});
  await assert.rejects(()=>form.save({COMPOSIO_API_KEY:KEY}),e=>e.status===409);
  assert.equal(C.readValues(s.user,'composio',conn.id).COMPOSIO_API_KEY,'new_concurrent_key_keep_me');
});
