const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'sc-hub-tests-'));process.env.SC_CONFIG_DIR=path.join(root,'config');
const P=require('../lib/profiles'),C=require('../lib/connections'),{PROVIDERS}=require('../lib/providers');const {startCredentialHub}=require('../lib/credential-manager');const {HUB_SCRIPT}=require('../lib/credential-manager-ui');
const SECRET='synthetic_opaque_composio_project_key';let n=0;
async function start(t,options={}){const user='hub-test-'+ ++n;P.writeProfile(user,{});const s=await startCredentialHub({user,check:async()=>({ok:true}),...options});t.after(()=>s.close());const token=new URL(s.url).hash.slice(1);const headers={Authorization:'Bearer '+token,Origin:s.origin,'Content-Type':'application/json'};return {...s,user,token,headers,call:async(action,args={})=>fetch(s.origin+'/api/action',{method:'POST',headers,body:JSON.stringify({action,...args})})};}
test.after(()=>fs.rmSync(root,{recursive:true,force:true}));
test('complete catalog exposes all providers and source methods, no credential values',async t=>{const s=await start(t);const r=await fetch(s.origin+'/api/catalog',{headers:s.headers});const d=await r.json();assert.equal(d.providers.length,PROVIDERS.length);assert.ok(d.providers.find(p=>p.id==='github').sources.some(x=>x.id==='composio'));assert.ok(!JSON.stringify(d).includes(s.token));assert.ok(!JSON.stringify(d).includes(SECRET));assert.doesNotThrow(()=>new Function(HUB_SCRIPT));});
test('public HTML works without embedding a capability; unknown origins and tokens fail',async t=>{const s=await start(t);const r=await fetch(s.origin);assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/connect-src 'self'/);assert.ok(!(await r.text()).includes(s.token));assert.equal((await fetch(s.origin+'/api/catalog')).status,401);const h={...s.headers,Origin:'https://evil.invalid'};assert.equal((await fetch(s.origin+'/api/action',{method:'POST',headers:h,body:'{}'})).status,403);});
test('new direct connection saves under correct user/provider/method and cannot be replayed',async t=>{const s=await start(t);const begin=await s.call('begin',{user:s.user,provider:'composio',newConnection:true,label:'Work project',auth:'project-api-key'});assert.equal(begin.status,200);const d=await begin.json();assert.deepEqual(d.schema.fields.map(f=>f.key),['COMPOSIO_API_KEY']);const r=await s.call('save',{session:d.session,values:{COMPOSIO_API_KEY:SECRET}});assert.equal(r.status,200);const saved=await r.json();assert.ok(!JSON.stringify(saved).includes(SECRET));assert.equal(C.readValues(s.user,'composio',saved.connection).COMPOSIO_API_KEY,SECRET);assert.equal(fs.statSync(C.connectionPath(s.user,'composio',saved.connection)).mode&0o777,0o600);assert.equal((await s.call('save',{session:d.session,values:{COMPOSIO_API_KEY:SECRET}})).status,401);});
test('project and organization methods can coexist without changing the existing key',async t=>{const s=await start(t);const conn=C.create(s.user,'composio',{label:'Project',source:'sc',authMethod:'project-api-key',scope:'project',setDefault:true});C.writeValues(s.user,'composio',conn.id,{COMPOSIO_API_KEY:SECRET});const d=await(await s.call('begin',{user:s.user,provider:'composio',auth:'organization-token',label:'Organization'})).json();assert.equal(d.schema.connection,null);assert.equal(d.schema.fields[0].key,'COMPOSIO_ORG_API_KEY');const r=await s.call('save',{session:d.session,values:{COMPOSIO_ORG_API_KEY:SECRET}});assert.equal(r.status,200);assert.equal(C.list(s.user,'composio').length,2);assert.deepEqual(C.readValues(s.user,'composio',conn.id),{COMPOSIO_API_KEY:SECRET});});
test('connection metadata CRUD is user-scoped and deletion requires explicit confirmation',async t=>{const s=await start(t);const args={user:s.user,provider:'github',label:'OAuth account',source:'composio',auth:'oauth2'};const r=await s.call('connectionAdd',args);assert.equal(r.status,200);const {connection}=await r.json();assert.equal((await s.call('rename',{user:s.user,provider:'github',connection,label:'Business OAuth'})).status,200);assert.equal(C.get(s.user,'github',connection).label,'Business OAuth');assert.equal((await s.call('remove',{user:s.user,provider:'github',connection})).status,400);assert.equal((await s.call('remove',{user:s.user,provider:'github',connection,confirm:connection})).status,200);assert.equal(C.list(s.user,'github').length,0);});
test('external connections never accept locally entered OAuth secrets',async t=>{const s=await start(t);const c=C.create(s.user,'github',{label:'External',source:'composio',authMethod:'oauth2',scope:'account',setDefault:true});const r=await s.call('begin',{user:s.user,provider:'github',connection:c.id});assert.equal(r.status,422);assert.equal((await r.json()).error,'external-authorization-required');});
test('unverifiable method requires a separate explicit save and is not labelled verified',async t=>{const s=await start(t,{check:async()=>({ok:null})});const b=await(await s.call('begin',{user:s.user,provider:'composio',newConnection:true})).json();assert.equal((await s.call('save',{session:b.session,values:{COMPOSIO_API_KEY:SECRET}})).status,422);assert.equal(C.list(s.user,'composio').length,0);const r=await s.call('save',{session:b.session,values:{COMPOSIO_API_KEY:SECRET},allowUnverified:true,confirmation:'SAVE UNVERIFIED'});assert.equal(r.status,200);assert.equal((await r.json()).verified,false);});
test('rejected credentials cannot use the unverified bypass',async t=>{const s=await start(t,{check:async()=>({ok:false})});const b=await(await s.call('begin',{user:s.user,provider:'composio',newConnection:true})).json();assert.equal((await s.call('save',{session:b.session,values:{COMPOSIO_API_KEY:SECRET},allowUnverified:true,confirmation:'SAVE UNVERIFIED'})).status,422);assert.equal(C.list(s.user,'composio').length,0);});
test('provider/field injection and oversized payloads are refused',async t=>{const s=await start(t);const b=await(await s.call('begin',{user:s.user,provider:'composio',newConnection:true})).json();assert.equal((await s.call('save',{session:b.session,values:{HOSTINGER_API_TOKEN:SECRET}})).status,422);assert.equal((await s.call('save',{session:b.session,values:{COMPOSIO_API_KEY:'x'.repeat(25000)}})).status,413);assert.equal((await s.call('save',{session:b.session,values:{COMPOSIO_API_KEY:SECRET},provider:'hostinger'})).status,400);});
test('a deleted connection is not resurrected by an old form',async t=>{const s=await start(t);const c=C.create(s.user,'composio',{label:'Delete me',source:'sc',authMethod:'project-api-key',scope:'project',setDefault:true});const b=await(await s.call('begin',{user:s.user,provider:'composio',connection:c.id})).json();C.remove(s.user,'composio',c.id);assert.equal((await s.call('save',{session:b.session,values:{COMPOSIO_API_KEY:SECRET}})).status,400);assert.equal(C.list(s.user,'composio').length,0);});

test('mounted HTTPS access may use a private path while retaining strict origin checks',async t=>{const s=await start(t);s.addPublicAccess({origin:'https://node.example.ts.net',basePath:'/sc-0123456789abcdef'});const host='node.example.ts.net';const html=await fetch(s.origin+'/sc-0123456789abcdef/',{headers:{Host:host}});assert.equal(html.status,200);const catalog=await fetch(s.origin+'/sc-0123456789abcdef/api/catalog',{headers:{Host:host,Origin:'https://node.example.ts.net',Authorization:'Bearer '+s.token}});assert.equal(catalog.status,200);const bad=await fetch(s.origin+'/sc-0123456789abcdef/api/catalog',{headers:{Host:host,Origin:'https://evil.invalid',Authorization:'Bearer '+s.token}});assert.equal(bad.status,403);assert.match(HUB_SCRIPT,/fetch\('api\/catalog'/);assert.doesNotMatch(HUB_SCRIPT,/fetch\('\/api\/catalog'/);});
