'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'sc-hostinger-mail-'));process.env.SC_CONFIG_DIR=path.join(root,'config');
const P=require('../lib/profiles'),C=require('../lib/connections'),H=require('../lib/hostinger-mail'),{PROVIDERS}=require('../lib/providers');
const USER='mail-test',TOKEN='synthetic-hostinger-token-0000000001',MAIL='synthetic-hostinger-mail-token-000001';
P.writeProfile(USER,{});
function conn(id,auth,values){const c=C.create(USER,'hostinger',{id,label:id,source:'sc',authMethod:auth,scope:auth==='mail-api-token'?'mail-order':'account',setDefault:false});C.writeValues(USER,'hostinger',c.id,values);return c;}
const account=conn('account','api-token',{HOSTINGER_API_TOKEN:TOKEN});const scoped=conn('mail','mail-api-token',{HOSTINGER_MAIL_API_TOKEN:MAIL,HOSTINGER_MAIL_ORDER_ID:'ORdemo'});
test.after(()=>fs.rmSync(root,{recursive:true,force:true}));
test('Hostinger provider exposes separate account and Mail API methods',()=>{const p=PROVIDERS.find(x=>x.id==='hostinger');assert.deepEqual(p.auth.map(x=>x.id),['api-token','mail-api-token']);assert.deepEqual(C.connectionFields(p,scoped).map(x=>x.key),['HOSTINGER_MAIL_API_TOKEN','HOSTINGER_MAIL_ORDER_ID']);});
test('account token lists mail orders without exposing the credential',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);const calls=[];global.fetch=async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify({data:[{id:'ORdemo'}]}),{status:200,headers:{'content-type':'application/json'}})};const out=await H.orders(USER,account.id);assert.equal(out.data.length,1);assert.equal(calls[0].url,'https://developers.hostinger.com/api/mail/v1/orders?per_page=100');assert.equal(calls[0].options.headers.Authorization,`Bearer ${TOKEN}`);assert.ok(!JSON.stringify(out).includes(TOKEN));});
test('scoped Mail connection is pinned to its order and supports allowlisted resources',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);let calls=0;global.fetch=async()=>{calls++;return new Response(JSON.stringify({data:[]}),{status:200,headers:{'content-type':'application/json'}})};await H.list(USER,scoped.id,'mailboxes',undefined);await assert.rejects(()=>H.list(USER,scoped.id,'mailboxes','ORother'),/does not match/);assert.equal(calls,1);});
test('secret-bearing Hostinger Mail operations are unreachable from machine mutation client',async()=>{await assert.rejects(()=>H.mutate(USER,account.id,'mailbox.create',{orderId:'ORdemo'}),/unsupported/);await assert.rejects(()=>H.mutate(USER,account.id,'webhook.create',{orderId:'ORdemo'}),/unsupported/);await assert.rejects(()=>H.mutate(USER,account.id,'api-token.create',{orderId:'ORdemo'}),/unsupported/);});
