'use strict';
const C=require('./connections');
const API='https://developers.hostinger.com/api/mail/v1';
const ID=/^[A-Za-z0-9._-]{3,128}$/;
const LIST=new Set(['mailboxes','aliases','forwarders','autoreplies','catchalls','webhooks']);
const LOGS=new Set(['access','action','inbound','mailbox-actions','outbound']);
const MUTATE=new Set(['alias.create','alias.delete','forwarder.create','forwarder.delete','forwarder.resend','forwarder.keep-copy','autoreply.create','autoreply.update','autoreply.delete','catchall.create','catchall.delete','catchall.resend','mailbox.delete']);
const rid=(v,n)=>{const s=String(v||'');if(!ID.test(s))throw Error(`invalid Hostinger Mail ${n}`);return s};
function selected(user,connection){const c=C.get(user,'hostinger',connection||C.selected(user,'hostinger')?.id);if(c.source!=='sc')throw Error('Hostinger Mail requires a direct SI-Coder connection');const v=C.readValues(user,'hostinger',c.id);const token=v.HOSTINGER_MAIL_API_TOKEN||v.HOSTINGER_API_TOKEN;if(!token)throw Error('Hostinger Mail credential is not configured');return{c,v,token};}
function orderId(v,input){const stored=v.HOSTINGER_MAIL_ORDER_ID,supplied=input?rid(input,'order id'):null;if(stored&&supplied&&stored!==supplied)throw Error('Hostinger Mail order does not match the selected connection');return stored||supplied;}
function redact(v,d=0){if(d>16)return'[depth limited]';if(Array.isArray(v))return v.map(x=>redact(x,d+1));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,/password|secret|token|authorization|api.?key/i.test(k)?'[redacted]':redact(x,d+1)]));return v;}
async function call(token,path,{method='GET',body}={}){const r=await fetch(API+path,{method,headers:{Authorization:`Bearer ${token}`,Accept:'application/json','Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'error',signal:AbortSignal.timeout(15000)});let out=null;try{out=await r.json()}catch{}if(!r.ok)throw Error(`Hostinger Mail HTTP ${r.status}`);return redact(out);}
async function orders(user,connection){const {v}=selected(user,connection);if(!v.HOSTINGER_API_TOKEN||v.HOSTINGER_MAIL_API_TOKEN)throw Error('Hostinger account API token required to list mail orders');return call(v.HOSTINGER_API_TOKEN,'/orders?per_page=100');}
async function list(user,connection,resource,order,page=1){if(!LIST.has(resource))throw Error('unsupported Hostinger Mail resource');const {v,token}=selected(user,connection),id=orderId(v,order);if(!id)throw Error('Hostinger Mail order id required');page=Math.max(1,Math.min(100,Number(page)||1));return call(token,`/orders/${encodeURIComponent(id)}/${resource}?page=${page}&per_page=100`);}
async function logs(user,connection,kind,order,page=1){if(!LOGS.has(kind))throw Error('unsupported Hostinger Mail log');const {v,token}=selected(user,connection),id=orderId(v,order);if(!id)throw Error('Hostinger Mail order id required');page=Math.max(1,Math.min(100,Number(page)||1));return call(token,`/orders/${encodeURIComponent(id)}/logs/${kind}?page=${page}&per_page=100`);}
const email=x=>{x=String(x||'').trim();if(x.length>254||!/^\S+@\S+\.\S+$/.test(x))throw Error('invalid email address');return x};
async function mutate(user,connection,operation,args={}){if(!MUTATE.has(operation))throw Error('unsupported Hostinger Mail mutation');const {v,token}=selected(user,connection);orderId(v,args.orderId);const box=()=>rid(args.mailboxId,'mailbox id'),id=k=>rid(args[k],k);switch(operation){case'alias.create':{const p=String(args.localPart||'').toLowerCase();if(!/^[a-z0-9](?:[a-z0-9._-]{0,48}[a-z0-9])?$/.test(p))throw Error('invalid alias local part');return call(token,`/mailboxes/${box()}/aliases`,{method:'POST',body:{local_part:p}})}case'alias.delete':return call(token,`/aliases/${id('aliasId')}`,{method:'DELETE'});case'forwarder.create':return call(token,`/mailboxes/${box()}/forwarders`,{method:'POST',body:{destination:email(args.destination),is_keep_copy_enabled:args.keepCopy===true}});case'forwarder.delete':return call(token,`/forwarders/${id('forwarderId')}`,{method:'DELETE'});case'forwarder.resend':return call(token,`/forwarders/${id('forwarderId')}/confirmation/resend`,{method:'POST'});case'forwarder.keep-copy':return call(token,`/forwarders/${id('forwarderId')}/keep-copy`,{method:'PATCH',body:{is_keep_copy_enabled:args.keepCopy===true}});case'autoreply.create':case'autoreply.update':{const subject=String(args.subject||''),body=String(args.body||'');if(!subject||subject.length>500||!body||body.length>20000)throw Error('invalid autoreply content');const payload={subject,body,...(args.displayName?{display_name:String(args.displayName).slice(0,255)}:{}),...(args.startsAt?{starts_at:String(args.startsAt)}:{}),...(args.endsAt?{ends_at:String(args.endsAt)}:{})};return operation.endsWith('create')?call(token,`/mailboxes/${box()}/autoreplies`,{method:'POST',body:payload}):call(token,`/autoreplies/${id('autoreplyId')}`,{method:'PUT',body:payload})}case'autoreply.delete':return call(token,`/autoreplies/${id('autoreplyId')}`,{method:'DELETE'});case'catchall.create':return call(token,`/mailboxes/${box()}/catchalls`,{method:'POST'});case'catchall.delete':return call(token,`/catchalls/${id('catchallId')}`,{method:'DELETE'});case'catchall.resend':return call(token,`/catchalls/${id('catchallId')}/confirmation/resend`,{method:'POST'});case'mailbox.delete':return call(token,`/mailboxes/${box()}`,{method:'DELETE'});}}
module.exports={orders,list,logs,mutate,LIST:[...LIST],LOGS:[...LOGS],MUTATE:[...MUTATE]};
