'use strict';
const fs=require('node:fs'),path=require('node:path');
const codec=require('./codec'),data=require('./data');
function safeFile(file){const abs=path.resolve(file);const fd=fs.openSync(abs,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const st=fs.fstatSync(fd);if(!st.isFile()||st.size>codec.MAX_BYTES)throw Error('invalid_or_oversized_import_file');return codec.parse(fs.readFileSync(fd,'utf8'));}finally{fs.closeSync(fd)}}
async function passphrase(askHidden,confirm){const first=await askHidden('Transfer passphrase (at least 12 characters): ',{escapeCancels:true});if(!first)return null;if(confirm){const again=await askHidden('Confirm transfer passphrase: ',{escapeCancels:true});if(first!==again)throw Error('passphrase_mismatch')}return first}
async function exportInteractive(includeSecrets,{askVisible,askHidden}){const date=new Date().toISOString().slice(0,10),name=`connections-${date}.integration-bundle${includeSecrets?'.enc':''}.json`;const chosen=await askVisible(`Output file [${name}]: `,{escapeCancels:true});if(chosen===null)return 'cancel';const out=path.resolve(chosen||name);let secret;try{if(includeSecrets){secret=await passphrase(askHidden,true);if(!secret)return 'cancel'}const bundle=await data.exportData({includeSecrets,passphrase:secret});fs.writeFileSync(out,JSON.stringify(bundle,null,2)+'\n',{mode:0o600,flag:'wx'});console.log(`✅ ${includeSecrets?'encrypted':'metadata'} export written: ${out}`);console.log(`   users: ${bundle.format===codec.ENCRYPTED?'encrypted':bundle.users.length} · credential values ${includeSecrets?'encrypted':'omitted'}`);return {file:out};}finally{secret=undefined}}
function showPreview(p){console.log('\nImport preview');console.log(`  producer    ${p.producer}`);console.log(`  users       ${p.createUsers.length} new`);console.log(`  connections ${p.connections.filter(x=>x.status==='create').length} create · ${p.connections.filter(x=>x.status==='skip').length} skip`);console.log(`  warnings    ${p.warnings.length}`);for(const r of p.connections.slice(0,20))console.log(`  ${r.status==='create'?'＋':'·'} ${r.user}/${r.provider}/${r.connection}${r.reason?` · ${r.reason}`:''}`);if(p.connections.length>20)console.log(`  … ${p.connections.length-20} more`)}
async function importInteractive({askVisible,askHidden,confirm}){const file=await askVisible('Import JSON file: ',{escapeCancels:true});if(file===null||!file)return 'cancel';const document=safeFile(file);let secret;try{if(document.format===codec.ENCRYPTED){secret=await passphrase(askHidden,false);if(!secret)return 'cancel'}const prefix=await askVisible('User ID prefix (blank keeps original IDs): ',{escapeCancels:true});if(prefix===null)return 'cancel';const opts={passphrase:secret,prefix:prefix||undefined,policy:'skip'},preview=await data.importData(document,opts);showPreview(preview);if(!preview.canApply){console.log('⚠ import cannot be applied under the current conflict policy');return}if(!(await confirm(`Apply this create-only import${preview.warnings.length?' and accept the listed warnings':''}?`))){console.log('cancelled');return 'cancel'}const result=await data.importData(document,{...opts,apply:true,confirm:preview.planId,acceptWarnings:preview.warnings.length>0});console.log(`✅ imported ${result.created} connection(s); imported connections are not marked verified`);if(preview.warnings.some(w=>w.reason==='external_authorization_required'))console.log('   external OAuth/provider connections require authorization again');return result}finally{secret=undefined}}
module.exports={exportInteractive,importInteractive};
